### ISSUE TITLE
Program hangs when trying to create Pump object.

### ISSUE THREAD

**Issue by redbort** [c0deba5e/nesp-lib-py#2]
Hello! This library appears to be exactly what I'm looking for, but I'm having some trouble getting things up and running.

Using some of the example code (see below), I am trying to create a Pump object, but the program seems to just hang indefinitely without raising any exceptions. I am using one of the New Era OEM pumps (model 511L) and running Python 3.12.4 and have tried this on both a Mac and PC (same version of Python). Any help troubleshooting would be much appreciated.

```
from nesp_lib import Port, Pump, PumpingDirection

port = Port('COM7')
# Constructs the pump connected to the port.
pump = Pump(port)
print("Pump object created.")  # this line does not execute.
```

**Comment by florian-lapp** [comment]
Hi redbort, this sounds like a baud rate issue. The pump might expect a different baud rate as the port is using. According to the user manual of the [New Era NE-500 series](https://www.syringepump.com/download/NE-500%20OEM%20Syringe%20Pump%20User%20Manual%20V3.9.pdf) the default baud rate is 19,200. The constructor of `Port` has an optional argument `baud_rate` for the baud rate:
https://github.com/florian-lapp/nesp-lib-py/blob/ca0a2295f2e6b197d74e075b04a45f180f43bf80/nesp_lib/port.py#L13-L26
The default value of `baud_rate` is 9,600, because other models use this value for the default baud rate:
https://github.com/florian-lapp/nesp-lib-py/blob/ca0a2295f2e6b197d74e075b04a45f180f43bf80/nesp_lib/port.py#L6-L7

Can you please try the following change?
```py
# Original
# port = Port('COM7')
port = Port('COM7', 19_200)
```

**Comment by redbort** [comment]
Thanks for the quick response! I tried specifying the baud rate as 19200, but the program still does not progress to the next line.

**Comment by yeu-lapp** [comment]
OK, maybe the pump is configured to another baud rate? Can you try all the possible values (19200 | 9600 | 2400 | 1200 | 300)?

If none is working, do you have the chance to find out if the serial communication on port COM7 between the computer and the pump is working at all? Maybe the port is somehow not configured correctly. On Windows I have used [Serial Debug Assistant](https://apps.microsoft.com/detail/9nblggh43hdm). You can try to send commands (see manual) via this software and see if you get anything back.

**Comment by redbort** [comment]
Oddly enough, it seems to be working just fine now… Thank you again for the extremely prompt responses - your help is much appreciated!

**Comment by yeu-lapp** [comment]
Cool! Glad I could help.
